server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: /Users/gilmar.alcantara/develop/alura/spring-cloud/config-server
