server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Gilmardealcantara/spring-cloud
          search-paths:
            - 'config-server/supplier'
